###-----------------------------------------------------------------------------------------------------------------  class(begin)
### TODO: 抛出错误
# 抛出Exception的实例. 是有意创建并抛出

class FooError(ValueError):
    pass

def foo(s):
    n = int(s)
    if n==0:
        raise FooError('invalid value: %s' % s)
    return 10 / n

foo('0')

###=================================================================================================================

